### ISSUE TITLE
[BUG] state of develop branch

### ISSUE THREAD

**Issue by ben-bay** [AIDungeon/AIDungeon#154]
As of 2pm today I seem to have managed to stabilize `develop`, meaning the installation, torrenting, and gameplay all work on [Colab](https://colab.research.google.com/github/AIDungeon/AIDungeon/blob/develop/AIDungeon_2.ipynb) with the branch changed to `--branch develop`.

I'm still trying to figure out why nested clones are appearing:
<img width="357" alt="Screen Shot 2019-12-13 at 2 12 57 PM" src="https://user-images.githubusercontent.com/48391872/70835841-3728e580-1db3-11ea-9eb6-3b5887c84a35.png">

**Comment by dyc3** [comment]
This happens if you run all the cells in the notebook multiple times. Here's what happens:

On the first run, 
1. git clone repo
2. cd AIDungeon
3. install... etc

When you run the first cell again, it doesn't check the current directory. The current working directory is already `./AIDungeon`. When git clone runs again, it doesn't care that it's already in a git repo, and it clones a new copy to `./AIDungeon/AIDungeon` and then `cd`s into that one.

**Comment by ben-bay** [comment]
@dyc3 lol embarassing if true.. I assumed it was that, but then upon exiting and revisiting a fresh notebook, the same thing occurred.

**Comment by dyc3** [comment]
Does the filesystem state persist even if you completely reset the notebook or wait a while for the notebook to time out?

**Comment by ben-bay** [comment]
@dyc3 I'm closing this, I think I freaked out prematurely
