### ISSUE TITLE
Training scripts?

### ISSUE THREAD

**Issue by justinglibert** [AIDungeon/AIDungeon#20]
Can you share the training scripts?
Contributing on the models would be much easier then!

**Comment by Akababa** [comment]
I believe it's in https://github.com/nickwalton/AIDungeon/blob/master/generator/simple/finetune.py

The author said he had 80MB of training data but there's only 30 here, though.

**Comment by justinglibert** [comment]
@Akababa apparently that's the old version. The code is using this [gpt2_generator.py](https://github.com/nickwalton/AIDungeon/blob/master/generator/gpt2/gpt2_generator.py) to generate the story. That's a custom version of GPT2. 
I don't think the training scripts are in the repo tho :/
Hope @nickwalton will reply to this!

**Comment by Akababa** [comment]
I'm also curious about what the role of > characters is in the training! Interesting to see if we can improve on finding a point to end generation.

**Comment by justinglibert** [comment]
It's basically a token to tell the model that the text following is a prompt :)

**Comment by nickwalton** [comment]
I'll try and clean up this code when I get more time. But as @Akababa said I did actually train with generator/simple/finetune.py and then just moved the model to the gpt2 folder. I thought I had said I only used 30 MB of training data? If I spoke wrong point me to where and I'll fix it.

@Akababa It's mostly used to indicate to the model that you just used an action. It also helps me cut off the text before the model generates a new action instead of just story.

**Comment by Akababa** [comment]
@nickwalton Oh I see, it was [this comment](https://news.ycombinator.com/item?id=21717621) on HN. I must have misread 8000000 as 80MB.

I noticed all the training data starts with "You", does this help? What happens if you remove the preprocessing from the training data and the prompts?

**Comment by nickwalton** [comment]
I did notice that adding "You" helped, but you would probably be able to
get good performance without it.

**Comment by nickwalton** [comment]
Training data has been removed due to copyright issues.
